# Generated by Django 6.0.7 on 2026-07-16 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guardian_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guardian',
            },
        ),
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('senior_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('diseases', models.TextField(blank=True)),
                ('medication', models.TextField(blank=True)),
                ('mobility_level', models.CharField(choices=[('independent', '독립'), ('partial_assist', '부분 보조'), ('full_assist', '완전 보조')], max_length=20)),
                ('barcode_code', models.CharField(max_length=100, unique=True)),
                ('fruit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'senior',
            },
        ),
        migrations.CreateModel(
            name='GuardianSeniorMap',
            fields=[
                ('map_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registered_via', models.CharField(choices=[('id_search', '아이디 검색'), ('barcode', '바코드 스캔')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(db_column='guardian_id', on_delete=django.db.models.deletion.CASCADE, to='api.guardian')),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, to='api.senior')),
            ],
            options={
                'db_table': 'guardian_senior_map',
                'unique_together': {('guardian', 'senior')},
            },
        ),
    ]
