# Generated by Django 6.0.7 on 2026-07-16 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움')], max_length=20)),
                ('guide_image_url', models.CharField(max_length=255)),
                ('silhouette_url', models.CharField(max_length=255)),
                ('reference_angles', models.JSONField()),
            ],
            options={
                'db_table': 'exercise',
            },
        ),
        migrations.CreateModel(
            name='ExerciseMission',
            fields=[
                ('mission_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', '대기'), ('completed', '완료'), ('skipped', '건너뜀')], default='pending', max_length=20)),
                ('exercise', models.ForeignKey(db_column='exercise_id', on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, to='api.senior')),
            ],
            options={
                'db_table': 'exercise_mission',
            },
        ),
    ]
