# Generated by Django 6.0.7 on 2026-07-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exercise_exercisemission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('completion_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accuracy_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(db_column='exercise_id', on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
                ('mission', models.ForeignKey(db_column='mission_id', on_delete=django.db.models.deletion.CASCADE, to='api.exercisemission')),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, to='api.senior')),
            ],
            options={
                'db_table': 'exercise_session',
            },
        ),
        migrations.CreateModel(
            name='PoseFeedback',
            fields=[
                ('feedback_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('joint_name', models.CharField(max_length=100)),
                ('deviation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='api.exercisesession')),
            ],
            options={
                'db_table': 'pose_feedback',
            },
        ),
        migrations.CreateModel(
            name='PhysicalAbilityLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rom_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completion_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('logged_date', models.DateField()),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, to='api.senior')),
            ],
            options={
                'db_table': 'physical_ability_log',
                'unique_together': {('senior', 'logged_date')},
            },
        ),
    ]
