# Generated by Django 6.0.7 on 2026-07-16 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exercisesession_posefeedback_physicalabilitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=100)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, to='api.senior')),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('fall', '낙상'), ('inactivity', '무활동'), ('sos', 'SOS')], max_length=20)),
                ('detection_source', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('detected', '감지됨'), ('first_check', '1차확인'), ('false_alarm', '오보'), ('notified', '긴급알림전송'), ('resolved', '종료')], default='detected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, to='api.senior')),
            ],
            options={
                'db_table': 'emergency_event',
            },
        ),
        migrations.CreateModel(
            name='CameraAccessGrant',
            fields=[
                ('grant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='api.emergencyevent')),
            ],
            options={
                'db_table': 'camera_access_grant',
            },
        ),
        migrations.CreateModel(
            name='EmergencyNotification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(default='fcm', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='api.emergencyevent')),
                ('guardian', models.ForeignKey(db_column='guardian_id', on_delete=django.db.models.deletion.CASCADE, to='api.guardian')),
            ],
            options={
                'db_table': 'emergency_notification',
            },
        ),
    ]
