# Generated by Django 6.0.7 on 2026-07-16 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activitylog_emergencyevent_cameraaccessgrant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSnapshot',
            fields=[
                ('snapshot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('snapshot_date', models.DateField()),
                ('rank_scope', models.CharField(choices=[('national', '전국'), ('regional', '지역')], max_length=20)),
                ('rank_position', models.IntegerField(blank=True, null=True)),
                ('senior', models.ForeignKey(db_column='senior_id', on_delete=django.db.models.deletion.CASCADE, to='api.senior')),
            ],
            options={
                'db_table': 'ranking_snapshot',
                'unique_together': {('senior', 'snapshot_date', 'rank_scope')},
            },
        ),
    ]
