# Generated by Django 6.0.7 on 2026-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rankingsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesession',
            name='accuracy_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='completion_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
