# Generated by Django 6.0.7 on 2026-09-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_exercise_pose_workout_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencynotification',
            name='channel',
            field=models.CharField(default='sms', max_length=50),
        ),
    ]
