# Generated by Django 6.0.7 on 2026-09-09 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_emergencynotification_channel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emergencynotification',
            unique_together={('event', 'guardian')},
        ),
    ]
