# Generated by Django 6.0.7 on 2026-09-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_emergencynotification_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesession',
            name='perceived_difficulty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
